version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4000:4000"
    expose:
      - 7000
    depends_on:
      - server_db
      - server_redis
    volumes:
      - ./server:/app

  server_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  server_redis:
    image: redis:latest
    ports:
      - "6379:6379"
