version: "3.4"
services:
  server_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=password

  server_redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dealer_client:
    build: ./dealer_client
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - server
    volumes:
      - ./dealer_client:/usr/src/app
    environment:
      - SERVER_URL=http://localhost:4000

  server:
    build: ./server
    ports:
      - "4000:4000"
    expose:
      - 4000
    depends_on:
      - server_db
      - server_redis
    volumes:
      - ./server:/usr/src/app
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_URL=${REDIS_URL}
      - REDIS_SECRET=${REDIS_SECRET}
      - JWT_SECRET=${JWT_SECRET}

  shopper:
    build: ./shopper
    ports:
      - "3001:3001"
    expose:
      - 3001
    depends_on:
      - server
    volumes:
      - ./shopper:/usr/src/app
    environment:
      - SERVER_URL=httpg://localhost:4000
